// Music images
export const imageSources = {
  falo: require("./images/music/falo.webp"),
  tramonto: require("./images/music/tramonto.jpg"),
  bosco: require("./images/music/bosco.jpg"),
  // Nuovi Aggiunti
  // pioggia: require("./images/music/pioggia.webp"),
  // alba: require("./images/music/alba.jpg"),
  // oceano: require("./images/music/oceano.webp"),
  // stelle: require("./images/music/stelle.jpg"),
  // montagna: require("./images/music/montagna.webp"),
  // deserto: require("./images/music/deserto.jpg"),
  // lago: require("./images/music/lago.webp"),
  // neve: require("./images/music/neve.jpg"),
  // libreria: require("./images/music/libreria.jpg"),
  // camino: require("./images/music/camino.webp"),
  // giungla: require("./images/music/giungla.jpg"),
  pioggia: require("./images/music/bosco.jpg"),
  alba: require("./images/music/bosco.jpg"),
  oceano: require("./images/music/bosco.jpg"),
  stelle: require("./images/music/bosco.jpg"),
  montagna: require("./images/music/bosco.jpg"),
  deserto: require("./images/music/bosco.jpg"),
  lago: require("./images/music/bosco.jpg"),
  neve: require("./images/music/bosco.jpg"),
  libreria: require("./images/music/bosco.jpg"),
  camino: require("./images/music/bosco.jpg"),
  giungla: require("./images/music/bosco.jpg"),
};
